apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
      - name: web
        image: jzaccone/webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    app: web 
  type: NodePort
  ports:
   - port: 5000
     nodePort: 31000
